[package]
name = "traffic-simulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = { version  = "0.35", features = ["ttf"] }
rustc-hash = "1.1"
rand = "0.8"