[package]
name = "re-router"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serial2 = "0.1"
lazy_static = "*"
image = "*"
sdl2 = { version  = "0.35", features = ["ttf", "image"] }